apps/patients/urls.py
from django.urls import path

from .views import dashboard, register_new_food

app_name = 'Patients'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('register_food/', register_new_food, name='register_food')
] 

saludable/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register_view, create_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.patients.urls')),
    path('register/', register_view, name='register'),
    path('create_user/', create_user, name='create_user')
]

apps/patients/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

YES_NO_CHOICES = [
    ('S', 'SI'),
    ('N', 'NO')
]


class Patients(models.Model):

    GENDERS = [
        ('M', 'Masculino'),
        ('F', 'Femenino')
    ]

    TREATMENTS = [
        ('A', 'Anorexia'),
        ('B', 'Bulimia'),
        ('O', 'Obesidad')
    ]

    dni = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDERS)
    date_of_birth = models.DateTimeField()
    location = models.CharField(max_length=100, null=True, blank=True)
    treatment = models.CharField(max_length=1, choices=TREATMENTS)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.surname}"


class DailyFood(models.Model):

    FOODS = [
        ('D', 'Desayuno'),
        ('A', 'Almuerzo'),
        ('M', 'Merienda'),
        ('C', 'Cena')
    ]

    date = models.DateField(blank=True,null=True)
    kind_of_food = models.CharField(max_length=1, choices=FOODS, default='D')
    primary_food = models.CharField(max_length=150, null=True, blank=True)
    secondary_food = models.CharField(max_length=150, null=True, blank=True)
    drink = models.CharField(max_length=100, null=True, blank=True)
    afters = models.CharField(
        max_length=1, choices=YES_NO_CHOICES, default='N')
    afters_name = models.CharField(max_length=150, null=True, blank=True)
    tentation = models.CharField(
        max_length=1, choices=YES_NO_CHOICES, default='N')
    tentation_name = models.CharField(max_length=150, null=True, blank=True)
    was_hungry = models.CharField(max_length=1, choices=YES_NO_CHOICES, default='N')
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.kind_of_food} - {self.date}"

    def get_name_of_type(self):
        for item in self.FOODS:
            if item[0] == self.kind_of_food:
                return item[1]
    
    def get_was_hungry(self):
        return 'SI' if self.was_hungry == 'S' else 'NO'
    
    def get_format_date(self):
        return self.date.strftime("%d/%m/%Y")
    
    def get_js_format_date(self):
        return self.date.strftime("%Y-%m-%d")

apps/patients/forms.py
from django.db.models.base import Model
from django import forms
from .models import DailyFood


class DailyFoodForm(forms.ModelForm):
    class Meta:
        model = DailyFood
        fields = ['date', 'kind_of_food', 'primary_food', 'secondary_food',
                  'drink', 'afters', 'afters_name', 'tentation', 'tentation_name', 'was_hungry']

        labels = {
            'date': 'Fecha:',
            'kind_of_food': 'Tipo de comida:',
            'primary_food': 'Comida principal:',
            'secondary_food': 'Comida secundaria:',
            'drink': 'Bebida:',
            'afters': '¿Ingirió postre?',
            'afters_name': '¿Qué postre?',
            'tentation': '¿Tuvo tentación de ingerir otro alimento?',
            'tentation_name': '¿Qué alimento?',
            'was_hungry': '¿Se quedó con hambre?'
        }

        widgets = {
            'date': forms.DateTimeInput(),
            'kind_of_food': forms.Select(attrs = {'class': 'form-control', 'required': 'required'}),
            'primary_food': forms.TextInput(attrs = {'class': 'form-control', 'required': 'required'}),
            'secondary_food': forms.TextInput(attrs = {'class': 'form-control'}),
            'drink': forms.TextInput(attrs = {'class': 'form-control'}),
            'afters': forms.Select(attrs = {'class': 'form-control', 'disabled': 'disabled'}),
            'afters_name': forms.TextInput(attrs = {'class': 'form-control', 'disabled': 'disabled'}),
            'tentation': forms.Select(attrs = {'class': 'form-control'}),
            'tentation_name': forms.TextInput(attrs = {'class': 'form-control', 'disabled': 'disabled'}),
            'was_hungry': forms.Select(attrs = {'class': 'form-control'}),
        }

apps/patients/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Count

import json
from datetime import datetime
import requests

from .models import DailyFood
from .forms import DailyFoodForm


@login_required
def dashboard(request):
    date_foods = DailyFood.objects.values('date').annotate(total=Count('date')).filter(user=request.user).order_by('-date')

    final_result = []
    result = []

    for date in date_foods:
        foods = DailyFood.objects.filter(user=request.user).filter(date=date['date'])
        
        for food in foods:
            result.append({
                'name': food.get_name_of_type(),
                'primary_food': food.primary_food,
                'secondary_food': food.secondary_food,
                'drink': food.drink,
                'afters': food.afters,
                'afters_name': food.afters_name,
                'tentation': food.tentation,
                'tentation_name': food.tentation_name,
                'was_hungry': food.was_hungry,
            })
        
        final_result.append({
            'date': date['date'].strftime('%d/%m/%Y'),
            'foods': result
        })

        result = []

    context = {
        'foods': final_result
    }

    return render(request, 'patients/dashboard.html', context=context)


@login_required
def register_new_food(request):

    if request.method == 'POST':
        received_data = json.loads(request.body)
        edit = True if request.headers['is-edit'] == 'true' else False
        first = True

        for info in received_data:
            
            date_register = datetime.strptime(info['date_register'], '%Y-%m-%d')

            if edit and first:
                try:
                    DailyFood.objects.filter(user=request.user).filter(date=date_register).delete()
                    first = False
                except:
                    return JsonResponse([{'status': 'error'}], safe=False)

            if not edit:
                exists = DailyFood.objects.filter(user=request.user).filter(
                    date=date_register).filter(kind_of_food=info['type'])

                if(exists):
                    return JsonResponse([{'status': 'error', 'message': f'Ya existe la entrada para {info["name"]} del día {info["date_register"]}'}], safe=False)

            daily_food = DailyFood()
            daily_food.kind_of_food = info['type']
            daily_food.primary_food = info['primary_food']
            daily_food.secondary_food = info['secondary_food']
            daily_food.drink = info['drink']
            daily_food.afters = info['afters']
            daily_food.afters_name = info['afters_name']
            daily_food.tentation = info['tentation']
            daily_food.tentation_name = info['tentation_name']
            daily_food.was_hungry = info['was_hungry']
            daily_food.date = date_register
            daily_food.user = request.user

            try:
                daily_food.save()
            except:
                return JsonResponse([{'status': 'error'}], safe=False)

        # Retorno el trago
        response = requests.get('https://www.thecocktaildb.com/api/json/v1/1/random.php')
        if response.status_code == 200:
            drink_api_response = response.json()
        else:
            drink_api_response = ""

        return JsonResponse([{'status': 'ok', 'drink_api': drink_api_response}], safe=False)

    elif request.method == 'GET':

        date_edit = request.GET.get('date','')
        foods = None
        date = None

        if date_edit:
            date = datetime.strptime(date_edit, '%d-%m-%Y')
            foods = DailyFood.objects.filter(user=request.user).filter(date=date)
            date = datetime.strftime(date, "%Y-%m-%d")

        form = DailyFoodForm()
        return render(request, 'patients/register_new_food.html', {'form': form, 'foods': foods, 'date_edit': date})

apps/patients/templates/patients/dashboard.html
{% extends 'base.html' %} {% load static %} {% load custom_tags %} 

{% block title %} Dashboard {% endblock %}
{% block navbar %} {% include 'navbar.html' %} {%endblock %} {% block content %}

<h3>Dashboard</h3>

<small>Aquí verá un detalle de las comidas agregadas en cada día.</small>
{% if foods %}
  {% for food in foods %}
  <button class="accordion">{{ food.date }}</button>
  <div class="panel">
    <a href="/register_food?date={{ food.date|replace_char_date }}">Editar</a>
    <div class="table-responsive">
      <table class="table table-bordered">
      <thead>
        <tr>
          <th>Tipo</th>
          <th>Principal</th>
          <th>Secundaria</th>
          <th>Bebida</th>
          <th>Postre</th>
          <th>Tentación</th>
          <th>Insatisfecho</th>
        </tr>
      </thead>

      <tbody>
        {% for type in food.foods %}

        <tr>
          <td>{{ type.name }}</td>
          <td>{{ type.primary_food }}</td>
          <td>{{ type.secondary_food }}</td>
          <td>{{ type.drink }}</td>
          <td>{{ type.afters_name }}</td>
          <td>{{ type.tentation_name }}</td>
          <td>{{ type.get_was_hungry }}</td>
        </tr>

        {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
  {% endfor %}
{% else %}
  <br><br>
  <a class="btn btn-success" href="{% url 'Patients:register_food' %}">Registrar Comida</a>
{% endif %}

{% block scripts_js %}
<script src="{% static 'patients/js/dashboard.js' %}"></script>
{% endblock %}

{% endblock %} {% block styles_css %}
<link rel="stylesheet" href="{% static 'patients/css/patients.css' %}" />
{% endblock styles_css %}

apps/patients/templates/patients/modal.html
<div
  class="modal fade"
  id="modalFoods"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Añadir nuevo alimento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <div id="modal_message" class="alert alert-danger" role="alert"></div>
          </div>
        </div>

        <form method="POST" action="{% url 'Patients:register_food' %}">
          {% csrf_token %} {{ form.non_field_errors }}

          <div class="row">
            <div class="col-md-6 col-xs-12">
              <div class="fieldWrapper">
                {{ form.date.errors }}
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
                <input id="id_date" class="form-control" type="date" value="{{ form.date.value }}" />
              </div>

              
              <div class="fieldWrapper">
                {{ form.kind_of_food.errors }}
                <label for="{{ form.kind_of_food.id_for_label }}"
                  >{{ form.kind_of_food.label }}</label
                >
                {{ form.kind_of_food }}
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.primary_food.errors }}
                <label for="{{ form.primary_food.id_for_label }}"
                  >{{ form.primary_food.label }}</label
                >
                {{ form.primary_food }}
              </div>
            </div>

            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.secondary_food.errors }}
                <label for="{{ form.secondary_food.id_for_label }}"
                  >{{ form.secondary_food.label }}</label
                >
                {{ form.secondary_food }}
              </div>
            </div>

            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.drink.errors }}
                <label for="{{ form.drink.id_for_label }}">{{ form.drink.label }}</label>
                {{ form.drink }}
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.afters.errors }}
                <label for="{{ form.afters.id_for_label }}">{{ form.afters.label }}</label>
                {{ form.afters }}
              </div>
            </div>

            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.afters_name.errors }}
                <label for="{{ form.afters_name.id_for_label }}"
                  >{{ form.afters_name.label }}</label
                >
                {{ form.afters_name }}
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.tentation.errors }}
                <label for="{{ form.tentation.id_for_label }}">{{ form.tentation.label }}</label>
                {{ form.tentation }}
              </div>
            </div>

            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.tentation_name.errors }}
                <label for="{{ form.tentation_name.id_for_label }}"
                  >{{ form.tentation_name.label }}</label
                >
                {{ form.tentation_name }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.was_hungry.errors }}
                <label for="{{ form.was_hungry.id_for_label }}">{{ form.was_hungry.label }}</label>
                {{ form.was_hungry }}
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="add_daily_food">Añadir</button>
      </div>
    </div>
  </div>
</div>

apps/patients/templates/patients/modal_drink.html
<div
  class="modal fade"
  id="modalDrinks"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Por utilizar nuestra app te regalamos esta receta!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal_drink_body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

apps/patients/templates/patients/register_new_food.html
{% extends 'base.html' %} {% load static %} {% load custom_tags %}
{% block title %} Registrar nuevo alimento {% endblock %}
{% block navbar %} 
{% include 'navbar.html' %} {%endblock %} {% block content %}

<h3>Nuevo registro de alimentos</h3>

<button type="button" class="btn btn-primary" id="btn_open_modal">Añadir alimentos</button>

<div class="row">
  <div class="col-md-12">
    <div id="message" class="alert" role="alert"></div>

    <small
      >Presione añadir alimentos para empezar a agregar sus comidas diarias. Una vez que cargue
      todas, presione grabar.</small
    >
    <div class="table-responsive">
      <table class="table table-bordered" id="table_foods">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Tipo de comida</th>
            <th>Principal</th>
            <th>Secundaria</th>
            <th>Bebida</th>
            <th>¿Ingirió postre?</th>
            <th>Postre</th>
            <th>¿Tuvo Tentación?</th>
            <th>Alimento</th>
            <th>¿Insatisfecho?</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody id="table_foods_body">
          
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 pt-10">
    <button type="submit" class="btn btn-success" id="btn_submit_food">Grabar</button>
  </div>
</div>

{% include 'patients/modal.html' %} {% include 'patients/modal_drink.html' %} {% endblock %} {% block styles_css %}
<link rel="stylesheet" href="{% static 'patients/css/patients.css' %}" />
{% endblock styles_css %} {% block scripts_js %}
<script src="{% static 'patients/js/patients.js' %}"></script>

{% if foods %}
<script>
  is_edit = true;
  date_edit = '{{ date_edit }}';

  {% for food in foods %}

      food = {
        type: '{{ food.kind_of_food }}',
        name: '{{ food.get_name_of_type }}',
        primary_food: '{{ food.primary_food }}',
        secondary_food: '{{ food.secondary_food }}',
        drink: '{{ food.drink }}',
        afters: '{{ food.afters }}',
        afters_name: '{{ food.afters_name }}',
        tentation: '{{ food.tentation }}',
        tentation_name: '{{ food.tentation_name }}',
        was_hungry: '{{ food.was_hungry }}',
        date_register: '{{ food.get_js_format_date }}'
      }

      daily_foods.push(food)

  {% endfor %}

  loadDailyFoodsInTable()
</script>
{% endif %} {% endblock scripts_js %}