apps/patients/urls.py
from django.urls import path

from .views import dashboard, register_new_food

app_name = 'Patients'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('register_food/', register_new_food, name='register_food')
] 

saludable/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register_view, create_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.patients.urls')),
    path('register/', register_view, name='register'),
    path('create_user/', create_user, name='create_user')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Saludable - {% block title %}Pacientes{% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />

    {% block styles_css %}

    {% endblock styles_css %}
  </head>
  <body>

    {% block navbar %}

    {% endblock navbar %}
    
    <div class="container">{% block content %} {% endblock %}</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    
    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts_js %}

    {% endblock scripts_js %}
  </body>
</html>

templates/navbar.html
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Saludable</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Patients:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Patients:register_food' %}">Registrar alimentos</a>
        </li>
      </ul>
      <div class="my-2 my-lg-0">
        {% if user.first_name %}
          Bienvendio {{ user.first_name }}!
        {% else %}
          Bienvendio {{ user.username }}!
        {% endif %}
        <p><a href="{% url 'logout' %}">(Cerrar sesión)</a></p>
      </div>
    </div>
  </nav>
</div>